// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: number.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PersonRequest) Reset() {
	*x = PersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRequest) ProtoMessage() {}

func (x *PersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRequest.ProtoReflect.Descriptor instead.
func (*PersonRequest) Descriptor() ([]byte, []int) {
	return file_number_proto_rawDescGZIP(), []int{0}
}

func (x *PersonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PersonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PersonReply) Reset() {
	*x = PersonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonReply) ProtoMessage() {}

func (x *PersonReply) ProtoReflect() protoreflect.Message {
	mi := &file_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonReply.ProtoReflect.Descriptor instead.
func (*PersonReply) Descriptor() ([]byte, []int) {
	return file_number_proto_rawDescGZIP(), []int{1}
}

func (x *PersonReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_number_proto protoreflect.FileDescriptor

var file_number_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23,
	0x0a, 0x0d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x39, 0x0a, 0x06,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x09, 0x53, 0x61, 0x79, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_number_proto_rawDescOnce sync.Once
	file_number_proto_rawDescData = file_number_proto_rawDesc
)

func file_number_proto_rawDescGZIP() []byte {
	file_number_proto_rawDescOnce.Do(func() {
		file_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_number_proto_rawDescData)
	})
	return file_number_proto_rawDescData
}

var file_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_number_proto_goTypes = []interface{}{
	(*PersonRequest)(nil), // 0: PersonRequest
	(*PersonReply)(nil),   // 1: PersonReply
}
var file_number_proto_depIdxs = []int32{
	0, // 0: Person.SayPerson:input_type -> PersonRequest
	1, // 1: Person.SayPerson:output_type -> PersonReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_number_proto_init() }
func file_number_proto_init() {
	if File_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_number_proto_goTypes,
		DependencyIndexes: file_number_proto_depIdxs,
		MessageInfos:      file_number_proto_msgTypes,
	}.Build()
	File_number_proto = out.File
	file_number_proto_rawDesc = nil
	file_number_proto_goTypes = nil
	file_number_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PersonClient is the client API for Person service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonClient interface {
	SayPerson(ctx context.Context, opts ...grpc.CallOption) (Person_SayPersonClient, error)
}

type personClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonClient(cc grpc.ClientConnInterface) PersonClient {
	return &personClient{cc}
}

func (c *personClient) SayPerson(ctx context.Context, opts ...grpc.CallOption) (Person_SayPersonClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Person_serviceDesc.Streams[0], "/Person/SayPerson", opts...)
	if err != nil {
		return nil, err
	}
	x := &personSayPersonClient{stream}
	return x, nil
}

type Person_SayPersonClient interface {
	Send(*PersonRequest) error
	Recv() (*PersonReply, error)
	grpc.ClientStream
}

type personSayPersonClient struct {
	grpc.ClientStream
}

func (x *personSayPersonClient) Send(m *PersonRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *personSayPersonClient) Recv() (*PersonReply, error) {
	m := new(PersonReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PersonServer is the server API for Person service.
type PersonServer interface {
	SayPerson(Person_SayPersonServer) error
}

// UnimplementedPersonServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServer struct {
}

func (*UnimplementedPersonServer) SayPerson(Person_SayPersonServer) error {
	return status.Errorf(codes.Unimplemented, "method SayPerson not implemented")
}

func RegisterPersonServer(s *grpc.Server, srv PersonServer) {
	s.RegisterService(&_Person_serviceDesc, srv)
}

func _Person_SayPerson_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PersonServer).SayPerson(&personSayPersonServer{stream})
}

type Person_SayPersonServer interface {
	Send(*PersonReply) error
	Recv() (*PersonRequest, error)
	grpc.ServerStream
}

type personSayPersonServer struct {
	grpc.ServerStream
}

func (x *personSayPersonServer) Send(m *PersonReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *personSayPersonServer) Recv() (*PersonRequest, error) {
	m := new(PersonRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Person_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Person",
	HandlerType: (*PersonServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayPerson",
			Handler:       _Person_SayPerson_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "number.proto",
}
